# Generated by Django 5.0.8 on 2024-08-09 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_item_item_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_descrip',
            new_name='item_describe',
        ),
    ]
